include .make/Makefile
include Makefile.backend-tests

vignettes/future.tests-01-intro.md: incl/OVERVIEW.md vignettes/incl/clean.css
	sed -E -i '/^(<!-- DO NOT EDIT THIS FILE|!\[|#+[[:space:]])/,$$d' $@
	echo "<!-- DO NOT EDIT THIS FILE! Edit '$<' instead and then rebuild this file with 'make vigettes' -->" >> $@
	cat $< >> $@
	sed -i 's/vignettes\///g' $@

vignettes: vignettes/future.tests-01-intro.md

spelling:
	$(R_SCRIPT) -e "spelling::spell_check_package()"
	$(R_SCRIPT) -e "spelling::spell_check_files(c('NEWS.md', dir('vignettes', pattern='[.](md|rsp)$$', full.names=TRUE)), ignore=readLines('inst/WORDLIST', warn=FALSE))"
